### ISSUE TITLE
Game List

### ISSUE THREAD

**Issue by JanAlSaifi** [DBr-git/game-flow#1]
## Value proposition
As a user
I want to browse a list of games,
so that I can see all my games in one place and stay organised.

## Description

![Image](https://github.com/user-attachments/assets/6d0d33ab-01e6-41e0-a275-d675bfc12223)

## Acceptance criteria
- The list page displays a list of games.
- The games list is headlined with its purpose.
- Each game listing includes:
  - Game title
  - Game rating
- Games are ordered by progress.
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks
- [ ] Create a feature-branch `feature/game-list`
- [ ] Create a dynamic GameList component displaying multiple cards 
- [ ] Import data from sample data
- [ ] Create a GameCard component displaying a game card with:  game title and rating
- [ ] Render a list for each label (in progess, planning, completed)
- [ ] Create a headline

**Comment by NikRoe** [comment]
Hi there,

this looks very promising! 🙌 

What can be seen in the wireframe, what is mentioned in the Acceptance Criteria and the Tasks, should always match.

I noticed that you mention that your GameCard component displays a priority and an image. This is not visible in the wireframe, neither is it mentioned in the Acceptance Criteria.
I would remove those two points from your tasks. 
In case of the priority, you don't need to display it in the card, since you already have the labels for "in progress" and "completed".
In case of the images, you would need to extend the dummy data with image links and when you want to create a new entry or update an existing entry, you would need to provide image links. 

Images can definitely be part of your application, but I would do it at a later point, since it will involve an image upload to some provider and that should be its own user story.
