### ISSUE TITLE
Create Game

### ISSUE THREAD

**Issue by DBr-git** [DBr-git/game-flow#5]
# Create Game

## Value Proposition

**As a user**

**I want to** create and store new games,

**so that** I can also keep track of games not shown in the list.

## Description

![Image](https://github.com/user-attachments/assets/f3f651d1-afb3-4348-87d3-f9c3e82fca61)

## Acceptance Criteria

- Button for adding games is displayed at the bottom of the games list page.
- User is redirected to create game page when clicking add button
- The form must include labelled inputs for:
  - Title
  - Rating
  - Description
- The following fields are mandatory:
  - Title
  - Rating
  - Description
- The rating can only be set with numbers from 0 - 10
- Progress defaults to the `planning` value
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Upon form submission, the new game is added to the game list at the appropriate position based on its progress.

## Tasks

- [ ] Create feature branch `feature/create-game`
- [ ] Add form page route
- [ ] Add a form element to form page
- [ ] Add required inputs for Game title, description, progress and rating (allowing numbers from 1 to 10)
- [ ] Progress defaults to the `planning` value
- [ ] Add a submit button with the text create to the form that allows for a onClick function
- [ ] Add a cancel button to cancel adding a game
- [ ] Handle submitting input data, store that data in a game card and add that card to the list according to the rating and progress
- [ ] redirect user to detail view of created game

**Comment by NikRoe** [comment]
Hi there,

nice work!

The Acceptance Criteria should describe the whole flow of the new feature, once it is implemented. The redirection of users to the detail view of the created game is currently missing. Please add this to the AC.

Edit: One thing that just came to my mind: Shouldn't users also be able to set a progress state when creating a new game? Because if a game has no progress state, where would it be displayed in the game list?

Aside from that, everything looks fine 🙌

**Comment by DBr-git** [comment]
Updated to include AC for redirection once user clicks the button.

Progress state gets set to a default value of `in progress` when adding a new game

**Comment by NikRoe** [comment]
> Progress state gets set to a default value of in progress when adding a new game

That is good to know! 

I would mention this in the User Story in the Acceptance Criteria and also in the Tasks.

Edit: Looks good with the adjustments ✅
