### ISSUE TITLE
Delete Game

### ISSUE THREAD

**Issue by DBr-git** [DBr-git/game-flow#6]
# Delete Game

## Value Proposition

**As a user**

**I want to** be able to delete games that are no longer relevant,

**so that** I can maintain a clean and organised game list, ensuring it’s always up to date.

## Description

![Image](https://github.com/user-attachments/assets/cd7f6470-c8c9-41b9-8bae-bda31c72f8ec)

## Acceptance Criteria

- Each game details view includes an easily accessible delete option.
- Clicking the delete option triggers a confirmation dialog.
- The dialog serves to prevent accidental deletions by asking the user to confirm their intention.
- The dialog includes options for both confirming the deletion and cancelling the action.
- The cancellation option allows the user to back out of the deletion process if selected by mistake or if they change their mind.
- Upon confirming the deletion, the user is immediately redirected to the overview of all games, and the game is removed from the list.
- If all games are deleted, a message appears indicating that there are no games and providing an option to add new ones.

## Tasks

- [ ] Create feature branch for Delete-Game.
- [ ] Add a delete button on each game details page.
- [ ] Create a dialog that appears prompt when the delete button is clicked. Include cancel and confirm options.
- [ ] Delete logic: On confirmation delete the game from the state.
- [ ] If no games left in Game List, display a message "No games available." Provide a button to add a new game when the list is empty.

**Comment by NikRoe** [comment]
Hi there,

nice work!

I would only adjust the wireframes, since there are currently two labels for "in progress". One of them should have a different label.

Edit: Looks good with the adjustments ✅
