### ISSUE TITLE
Update Game

### ISSUE THREAD

**Issue by DBr-git** [DBr-git/game-flow#7]
# Update Game

## Value Proposition

**As a user**

**I want to** update the details of existing games,

**so that** they reflect the most accurate and relevant information.

## Description

![Image](https://github.com/user-attachments/assets/61759a7a-e1ba-440e-b4c3-190c27728234)

## Acceptance Criteria

- Each game details page includes an easily accessible edit option.
- Clicking the edit option opens a new page with a form pre-filled with the game’s existing details for modification.
- The form allows for edits to all game details, including:
  - title
  - description
  - rating
- The following fields are mandatory:
  - title
  - description
  - Rating
- The form section includes options for both saving and cancelling the action.
- The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- Submissions with empty required fields are blocked, with validation messages indicating the missing required fields.
- Upon confirming the save, the user is immediately redirected to the details page of the edited game, and the changes are saved and reflected.

## Tasks

- [ ] Create feature branch `feature/update-game`
- [ ] Add edit page / route
- [ ] Add edit button redirecting to the edit page
- [ ] reuse create game form but set default values to the game being edited
- [ ] handle edited data and update stored values
- [ ] handle onClick event redirecting to each detail page after handling edited data

**Comment by NikRoe** [comment]
Hi there,

this looks good! 

I would make a slight adjustment to the wireframe.
In your AC you mention that the form is pre-filled with all the information, this should be reflected in the wireframe.

I would also add the progress state of the game to the form, in case users want to update it while editing other parts of the game. This should then be part of the AC and the wireframe.

Edit: Looks good with the adjustments ✅
