### ISSUE TITLE
Set Game Progress

### ISSUE THREAD

**Issue by DBr-git** [DBr-git/game-flow#8]
# Set Game Progress

## Value Proposition

**As a user**

**I want to** set a game's progress,

**so that** I can easily monitor which games I’ve started, completed, or plan to play next.

## Description

![Image](https://github.com/user-attachments/assets/1484bfe1-88fb-4863-89d0-a0bfbb7ecced)

## Acceptance Criteria

- Each game includes a Select element to mark the game as completed, in progress or planning , available on the detail page.

## Tasks

- [ ] Create feature branch `feature/mark-game-completed`
- [ ] Add a Select element to the detail page
- [ ] Add three options to the select element: "completed", "In progress", "planning"
- [ ] The selectors initial value is set with the "progress" value of the game the user is currently selecting.
- [ ] Write a handler which updates the progress key in the "InitialGameList"  depending on the selected value in the Selector

**Comment by NikRoe** [comment]
Hi there,

nice work 🙌 

I would make some small adjustments that only arise since we changed from Task-Flow to Game-Flow:

I would change the title of the issue from "Mark Game as Complete" to "Set Game Progress".

I would update the Value Proposition to this:

As a user
I want to set a game's progress,
so that I can easily monitor which games I’ve started, completed, or plan to play next.

Edit: Looks good with the adjustments ✅
