### ISSUE TITLE
Sort Games

### ISSUE THREAD

**Issue by DBr-git** [DBr-git/game-flow#9]
# Sort Games

## Value Proposition

**As a user**
**I want to** sort games alphabetically or by rating,
**so that**  I can quickly find specific games or prioritize highly rated ones.

## Description

![Image](https://github.com/user-attachments/assets/52e692b0-077b-48ab-b35c-3b6067aa6cf7)

## Acceptance Criteria

- The game list includes a dropdown menu with sort options.
- Users can sort games in ascending order.
- The applied sort order is clearly displayed on the game list, allowing users to see the current sort criterion.
- Users can change the order with a single click, returning to other the list.
- The game list updates in real-time as the sort option is applied or changed.
- The sorting interface is intuitive and easy to use, ensuring that new users can easily understand how to apply and change the sort order.

## Tasks

- [ ] Create feature branch `feature/sort-games`
- [ ] Add a dropdown menu
- [ ] Add a useState to track changes
- [ ] Create a handler function that can sort the games alphabetically or by rating
- [ ] Connect the dropdown menu with the function

**Comment by NikRoe** [comment]
Hi there,

nice start! Some things need slight adjustment:

### Value Proposition:

The Value Proposition is currently a mixture of the task-flow and game-flow app. I would change it to this:

As a user,
I want to sort games alphabetically or by rating,
so that I can quickly find specific games or prioritize highly rated ones.

### Wireframe:

The Wireframe has two labels with "in progress". You probably want to change one of them to "planned".

### Acceptance Criteria:

The Acceptance Criteria still mentions elements from the task-flow, such as "priority". You probably want to change this to reflect how games can actually be sorted by.

### Tasks:

The Tasks still mention "Capstone Group Todo: Add tasks", you can remove this bullet point.

### General Notes:

In the Task-Flow App, this feature only includes one sort option, while your App has two sort options.
While it seems like a small thing to add a second sort option, it might take more time to implement than appears at first glance. 
I would highly recommend splitting this user story into two separate stories. 

The first one would only implement one sort option and could be considered a basic sorting option.
The second one would implement a second sort option and could be considered an advanced sort option.

**Comment by DBr-git** [comment]
> ### General Notes:
> In the Task-Flow App, this feature only includes one sort option, while your App has two sort options. While it seems like a small thing to add a second sort option, it might take more time to implement than appears at first glance. I would highly recommend splitting this user story into two separate stories.
> 
> The first one would only implement one sort option and could be considered a basic sorting option. The second one would implement a second sort option and could be considered an advanced sort option.

We were not sure if you noticed that we initially thought we would sort the list by rating in the Game List user story already.
Since your suggestion we adapted it in a way that the initial list is unsorted and we have an option to sort it by rating asscending/descending.
Would this work better?

**Comment by NikRoe** [comment]
I did not notice, thanks for pointing this out! 

I like how it looks now. 👌 ✅
